### ISSUE TITLE
Problem with CSS pseudo-element with "-" (first-child, last-child etc.)

### ISSUE THREAD

**Issue by KacperKozak** [andreypopp/react-css-components#14]
Pseudo-element with `-` don't work properly.

eg.:

``` css
Label:first-child {
    border-left: none;
}
```

In transpiled file looks like this:

``` js
// ...
var className = styles.Label + (variant.first-child ? ' ' + styles.Label__first-child : '');
// ...
```

And selector will be: `.Label__first-child---36X92`.
